### ISSUE TITLE
Command failed /tmp/node_modules/electron/dist/electron: No such file or directory

### ISSUE THREAD

**Issue by luisnquin** [diciaup/assistant-cli#2]
**Describe the bug**
Apparently the CLI is not correctly executed when called

**AssistantCli Version**
Add the version of your AssistantCli

**To Reproduce**
1. Launch command 'npx assistant-cli || npm install assistant-cli'
2. This error is displayed:
```console
Error: Command failed: /tmp/node_modules/electron/dist/electron --no-logging /tmp/node_modules/assistant-cli/dist/fetch-token.js
/bin/sh: línea 1: /tmp/node_modules/electron/dist/electron: No such file or directory

    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at getToken (/tmp/node_modules/assistant-cli/dist/app.js:25:21)
    at /tmp/node_modules/assistant-cli/dist/app.js:58:18
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/node_modules/assistant-cli/dist/app.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 127,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 2f 62 69 6e 2f 73 68 3a 20 6c c3 ad 6e 65 61 20 31 3a 20 2f 74 6d 70 2f 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 65 6c 65 63 74 72 6f 6e 2f 64 69 73 74 ... 37 more bytes>
  ],
  pid: 9219,
  stdout: <Buffer >,
  stderr: <Buffer 2f 62 69 6e 2f 73 68 3a 20 6c c3 ad 6e 65 61 20 31 3a 20 2f 74 6d 70 2f 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 65 6c 65 63 74 72 6f 6e 2f 64 69 73 74 ... 37 more bytes>
}


```

**Expected behavior**
The program runs normally

**Screenshots**
![image](https://user-images.githubusercontent.com/86449787/209454427-86af8efd-86a0-400e-b2b5-af6900579976.png)

**CLI (please complete the following information):**
 - OS: NixOS 
 - OS Version 23.05

**Comment by diciaup** [comment]
Thanks for the feedback! It will be solved on next release
